FZ13, pull-request-1
StopTheClocks4ever/java-shareit pull request #1
Opened 2024-03-31 10:11 UTC by StopTheClocks4ever

2024-03-31 17:01 UTC, mikita95 requested changes
Все отлично  :) Оставил лишь небольшие замечания

2024-03-31 17:01 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    @Autowired
Autowired лучше не использовать над полями, это является рекомендацией спринга, лучше использовать конструктор

2024-03-31 17:01 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item addItem(@RequestBody @Valid ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") int ownerId) {
Нужно возвращать dto, контроллер не должен знать о сущностях базы данных

2024-04-01 19:57 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    @Autowired
Выполнил

2024-04-01 19:58 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item addItem(@RequestBody @Valid ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") int ownerId) {
Выполнил

2024-04-02 20:29 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-04-08 18:39 UTC, merged