Add bookings
StopTheClocks4ever/java-shareit pull request #3
Opened 2024-04-17 14:34 UTC by StopTheClocks4ever

2024-04-17 22:11 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-04-17 22:11 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    @Autowired
Лучше не использовать Autowired над полями, спринг рекомендует использовать конструкторы для этого

2024-04-17 22:11 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Лучше не использовать Data над сущностями hibernate, так как это сгенерирует методы toString и hashCode, что может привести к инициализации lazy полей, а также к циклическим вызовам

2024-04-17 22:11 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<ResponseBookingDto> getAllUsersBookings(int usersId, String state) {
Лучше было бы завести enum для state

2024-04-17 22:11 UTC, mikita95 commented on src/main/resources/schema.sql
> +
Можно добавить индексы на колонки, по которым часто выполняются запросы, так будет эффективнее

2024-04-19 15:50 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    @Autowired
Выполнено

2024-04-19 15:55 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Выполнено

2024-04-19 16:52 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<ResponseBookingDto> getAllUsersBookings(int usersId, String state) {
Выполнено

2024-04-19 17:10 UTC, StopTheClocks4ever commented on src/main/resources/schema.sql
> +
Выполнено

2024-04-20 21:42 UTC, mikita95 requested changes
Все отлично :) Оставил лишь небольшие замечания

2024-04-20 21:42 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private BookingService bookingService;
Поле можно сделать final

2024-04-20 21:42 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingController(BookingService bookingService) {
Можно использовать аннотацию lombok RequiredArgsConstructor, чтобы не создавать конструктор руками

2024-04-20 21:42 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state.equals(State.REJECTED)) {
Можно использовать конструкцию switch-case, чтобы не дублировать if

2024-04-20 21:42 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                lastBooking = null;
Можно использовать isEmpty лучше, так будет понятнее

2024-04-21 13:29 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private BookingService bookingService;
Выполнено

2024-04-21 13:29 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingController(BookingService bookingService) {
Выполнено

2024-04-21 13:41 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state.equals(State.REJECTED)) {
Выполнено

2024-04-21 13:56 UTC, StopTheClocks4ever commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                lastBooking = null;
Выполнено

2024-04-21 21:12 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-04-25 08:35 UTC, merged